services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD: /run/secrets/db_password
    healthcheck:
      test: mysqladmin ping -h localhost --password="$(cat /run/secrets/db_password)"
    secrets:
      - db_password

secrets:
  db_password:
    file: ${DB_PASSWORD_SECRETS_FILE:?No db secret file set}
