services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=web
      - traefik.http.routers.frontend-http.rule=HostRegexp(`{any:.+}`)

  proxy:
    image: traefik:v3.6
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      # Keep v2 rule syntax for now 
      # Ensure compatibility with existing labels (will be removed if v3 transistion is complete)
      - --core.defaultRuleSyntax=v2
      - --entrypoints.web.address=:80
    ports:
      - ${HTTP_PUBLISH_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: host
