#!/bin/bash

if [[ $# -eq 0 ]]; then
    docker exec -it frappe bash
elif [ "$1" == 'init' ]; then
    docker exec -it -u root frappe bash -c "cd /home/frappe && chown -R frappe:frappe ./*"
    docker exec -i frappe bash -c "cd .. && bench init frappe-bench --ignore-exist --skip-redis-config-generation"
    docker exec -i frappe bash -c "mv Procfile_docker Procfile && mv sites/common_site_config_docker.json sites/common_site_config.json && bench set-mariadb-host mariadb"
elif [ "$1" == 'setup' ] && [ "$2" == 'docker' ]; then
    if [ "$3" == '--swarm-mode' ]; then
        echo "Docker swarm mode is not currently supported"
    else
        docker-compose up -d
    fi
elif [ "$1" == '-c' ]; then
    shift
    user=$1
    shift
    docker exec -i -u "$user" frappe bash -c "$@"
else
    IFS=" "
    docker exec -i frappe bash -c "bench $*"
fi