#!/bin/bash
set -euo pipefail

# Default values
BACKEND=${BACKEND:-0.0.0.0:8000}
SOCKETIO=${SOCKETIO:-0.0.0.0:9000}
UPSTREAM_REAL_IP_ADDRESS=${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
UPSTREAM_REAL_IP_HEADER=${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
UPSTREAM_REAL_IP_RECURSIVE=${UPSTREAM_REAL_IP_RECURSIVE:-off}
FRAPPE_SITE_NAME_HEADER=${FRAPPE_SITE_NAME_HEADER:-$host}
PROXY_READ_TIMEOUT=${PROXY_READ_TIMEOUT:-120}
CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE:-50m}

# Generate nginx configuration
envsubst '${BACKEND}
  ${SOCKETIO}
  ${UPSTREAM_REAL_IP_ADDRESS}
  ${UPSTREAM_REAL_IP_HEADER}
  ${UPSTREAM_REAL_IP_RECURSIVE}
  ${FRAPPE_SITE_NAME_HEADER}
  ${PROXY_READ_TIMEOUT}
  ${CLIENT_MAX_BODY_SIZE}' \
  < /templates/nginx/frappe.conf.template > /etc/nginx/conf.d/frappe.conf

# Start nginx
exec nginx -g 'daemon off;'
