name: Legacy / Build Develop

on:
  workflow_dispatch:

jobs:
  delegate:
    uses: ./.github/workflows/core-build-develop.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
