name: Legacy / Build Stable

on:
  workflow_dispatch:

jobs:
  delegate:
    uses: ./.github/workflows/core-build-stable.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
